version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.0

executors:
  my-exec:
    docker:
      - image: ubuntu:latest
        name: eks-testing
        auth:
          username: dsouzaj98
          password: $DOCKERHUB_PASSWORD

jobs:
  cfn-launch:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          command: |
            echo Building CloudFormation Template
            aws cloudformation create-stack \
            --template-url https://cf-templates-16lz765g5qw3s-us-east-1.s3.amazonaws.com/2021094f6k-eks.yml \
            --stack-name johann-eks-test \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn arn:aws:iam::396791034774:role/eks-testing \
          

  cfn-lint:
    executor: my-exec
    steps:
      - run:
          command: |
            echo Running test
            apt-get install cfn-lint && cfn-lint ~/Documents/vertical_relevance/CircleCI-intro/cfn/eks.yml  
          # check location of this image



workflows:
 version: 2
 Example_Workflow:
   jobs:
      - cfn-launch:
          context:
            - aws
      - cfn-lint:
          context: 
            - docker
          requires:
            - cfn-launch
#change to cfn-launch requires cfn-lint