version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.0
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  cfn-launch:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          command: |
            echo Building CloudFormation Template
            aws cloudformation create-stack \
            --template-url https://cf-templates-16lz765g5qw3s-us-east-1.s3.amazonaws.com/2021094f6k-eks.yml \
            --stack-name johann-eks-test \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn arn:aws:iam::396791034774:role/eks-testing \
          #find errorof  

  cfn-lint:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          command: |
            echo Running test
            pip install cfn-lint && cfn-lint cfn/eks.yml  
          # check location of this image

  taskcat:


workflows:
 version: 2
 Example_Workflow:
   jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - cfn-launch:
          context:
            - aws
      - cfn-lint:
          requires:
            - cfn-launch


    
    #  - Run-With-Node:
    #      requires:
    #        - Hello-World
    #  - Hold-For-Approval:
    #      type: approval
    #      requires:
    #        - Run-With-Node
    #        - I-Have-Code
    #  - Now-Complete:
    #      requires:
    #        - Hold-For-Approval